### PR TITLE
major reformation of generated class structure

### PR DESCRIPTION
**Pull request by pmjones**
@froschdesign and others -- This PR proposes a reformed class structure for Atlas.Table generated classes. It is intended for the 2.x series going to the overall Dymaxion (v4) package set.

I believe these changes make it easier to see, from filenames/classnames alone, what files are generated and not-to-be-touched, and what files are safe to edit. In short:

- anything in the `_` directory or namespace is generated; all others are open for editing.
- all classes get a generated parent/intercessor class, instead of some and not others

The two major drawbacks are (1) is it non-standard to use underscores, especially standalone underscores, in namespaces and class names, and (2) it is a major, significant, substantial break from the prior Atlas structures. There will have to be some sort of conversion script or manual for users coming from Cassini (v3) to Dymaxion (v4).

If you have the time and energy, please look these over and let me know what you think. Spare no criticism, please.

Thanks and I hope you are all doing well. :-)

### CODE REVIEW

**Comment by froschdesign** [comment]
@pmjones 
_Sorry for the very late response!_

> The two major drawbacks are (1) is it non-standard to use underscores, especially standalone underscores, in namespaces and class names…

I have been thinking about the issue for a while and I find it problematic. You are right, it is not standardised and that is why I tried to find an alternative, which is not _so exotic_ and which is supported by an IDE.
I have therefore looked at the DocBlock annotations:

## `@internal`

The first idea was to use `@internal` for the generated classes.

> The @internal tag is used to denote that associated Structural Elements are internal to the application or library. It may also be used inside a long description to insert a piece of text that is only applicable for the developers of the software.

https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/internal.html#internal

But this would not work for an application which uses Atlas in PHPStorm:

> * In a project with no source roots, no @internal class usages will be marked.
> * If a source root is configured and the @internal class is located inside it, the usages inside this source root won’t be marked, but usages outside this source root will be marked.

The generated classes are all located in the source root of a PHPStorm project.

Reference: https://blog.jetbrains.com/phpstorm/2018/12/phpstorm-2018-3-1-is-released/

## `@ignore`

The `@ignore` tag is already excluded by definition:

> The @ignore tag is used to tell phpDocumentor that Structural Elements are not to be processed by phpDocumentor.

https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/ignore.html#ignore

## `@deprecated`

The `@deprecated` is interesting because the description of this tag contains an useful part:

> The `@deprecated` tag declares that the associated Structural Element(s) will be removed in a future version as it has become obsolete **or its usage is otherwise not recommended**, effective from the "Semantic Version" if provided.

_"or its usage is otherwise not recommended"_ – It could be interpreted that this could match to the automatically generated classes.

If a class can be overwritten in the future, then the current version can already be considered deprecated.
And if a class is marked as deprecated, its name will be shown as strike through. I think this should work in most IDE's, like PHPStorm, Visual Studio Code with PHP Intelephense and others like Netbeans.

---

The problem with a DocBlock annotation is that you cannot see from the class name alone if it is a class that should not be touched. Especially if you don't have the support of an IDE.
But an underscore by itself does not say much either. 😉

**Comment by pmjones** [comment]
@froschdesign --

> Sorry for the very late response!

Not at all; thanks for taking the time! Yes, it's a sticky problem.

I don't think docblocks will solve the trouble I see; namely, that the directory for each table gets *really* filled up, making it hard to see what is intended-to-be-edited and what is intended-to-be-regenerated. I thought about using a prefix or suffix on classes and keeping them all in the same directory, e.g. `Row.php` for the user-editable file and `_Row.php` or `Row_.php` for the generated one, but that doesn't reduce the number of files in the directory. Putting them in *some* sort of subdirectory really does seem the way to go.

I like the underscore because it is short, and keeps the generated classes out of the way, but you're right, it is just not obvious from first-reading what the purpose is.

Maybe replace `_` with `_generated` or `_base` or something like that? That might be more-obvious, and keeps the generated classes in a separate space.

**Comment by froschdesign** [comment]
@pmjones 
> Maybe replace `_` with `_generated` or `_base` or something like that?

Will this be enough to say: "please do not change this class"? However, all other classes are also generated / created automatically.

**Comment by pmjones** [comment]
> Will this be enough to say: "please do not change this class"?

Kind of -- one of the goals I'd like to achieve is a "physical" separation of the generated from the non-generated. For example, mixing them in the same directory, you get something like this:

```

Row.php
Row_generated.php
Table.php
Table_generated.php
Select.php
Select_generated.php
```

What I'd like is something more like this:

```
Row.php
Table.php
Select.php
_generated/
	Row_.php
	Table_.php
	Select_.php
```

That keeps all the generated not-to-be touched stuff separate from the stuff it's OK to mess with.

(Adding "do not touch" markers in addition to that won't hurt, though.)

Do you see what I'm getting at here? And do you think that separation is a worthwhile goal?

**Comment by froschdesign** [comment]
> Do you see what I'm getting at here?

Sure, and I have no problem separating these classes from the others. (autoloading must work)
It would at least give a signal that something is different here or that needs to be respected.

**Comment by pmjones** [comment]
@froschdesign Excellent. So the main problem now is the namespace name for the generated classes. I like `_` because it is short, and there is some symmetry to (e.g.) `extends _\Row_`. Something like `extends _generated\Row_` is just as symmetrical, but longer -- although "longer" is not necessarily bad. Do you have thoughts on alternative namespace names here?

Also @kevinsmith do you have any input here?

**Comment by kevinsmith** [comment]
I like the idea of more cleanly separating the Atlas code from the application code. Including the word "generated" does seem to be enough of a signal to encourage devs to look into it if they're not sure what's going on with the classes in that namespace. I would support that.

I'm assuming that the skeleton would now be generating all these classes on the first go and then only re-generating the classes in the `_generated` on subsequent runs. Is that right?

**Comment by pmjones** [comment]
> I'm assuming that the skeleton would now be generating all these classes on the first go and then only re-generating the classes in the _generated on subsequent runs. Is that right?

Correct!

**Comment by pmjones** [comment]
With all the above in mind, I think moving from `_\Whatever_.php` to `_generated\Whatever_.php` is the way to go. Any further comments or criticism @froschdesign @kevinsmith (or others) ?

**Comment by kevinsmith** [comment]
Any reason for going with lowercase `_generated`? Prevailing convention and the norm within the Atlas codebases seems to be StudlyCaps.

**Comment by pmjones** [comment]
The reason, if you can call it that, is that I *want* it to look unusual -- "this is weird, don't mess with it."

**Comment by kevinsmith** [comment]
Ah, well good enough!

**Comment by froschdesign** [comment]
@pmjones 
> `_generated\Whatever_.php`

I still struggle with "generated" because all classes are generated / created automatically. (see https://github.com/atlasphp/Atlas.Table/pull/11#issuecomment-889881903)

Another idea: `_auto_updated\Whatever_.php`

**Comment by pmjones** [comment]
> I still struggle with "generated" because all classes are generated 

Ah, I see your point -- you see a distinction between "generated the first time" and "regenerated over and over as needed". Thus, "_autoupdated" to recognize that distinction.

/me furrows brow

On the one hand, I get where you're coming from.

On the other hand, I get the feeling that everyone will understands immediately (or very quickly) what "_generated" means here; i.e., "regenerated from time to time."

I'm open to entertaining other short single words to replace "generated". @froschdesign thoughts?

(p.s. This is one more reason that a single underscore, though unusual and atypical, might still be the better choice -- no terminology issues associated with it.)

**Comment by froschdesign** [comment]
@pmjones 
> …you see a distinction between "generated the first time" and "regenerated over and over as needed".

Right.

> On the other hand, I get the feeling that everyone will understands immediately (or very quickly) what "_generated" means here; i.e., "regenerated from time to time."

I agree with the argument; this means I'm also fine with "_generated". 👍

**Comment by kevinsmith** [comment]
> On the other hand, I get the feeling that everyone will understands immediately (or very quickly) what "_generated" means here; i.e., "regenerated from time to time."
> 
> I'm open to entertaining other short single words to replace "generated".

Well, since it's the word you're using to define what you mean here... what about `_regenerated`?

**Comment by pmjones** [comment]
/me furrows brow at "_regenerated"

Maybe? Although I think at this point, @froschdesign and I both think that `_generated` will be well-understood, more so than `_` for sure, and obvious-enough.

Even so: other thoughts on names @kevinsmith ?

**Comment by kevinsmith** [comment]
No objections.

**Comment by froschdesign** [comment]
@pmjones 
There are some more people with the same problem: https://github.com/ezimuel/fig-standards/blob/psr-19/generated/proposed/phpdoc-tags.md#55-generated

---

The official pull request: https://github.com/php-fig/fig-standards/pull/1249

**Comment by froschdesign** [comment]
@pmjones 
Based on the proposed PSR-19 standard, "generated" is the right choice:

> The `@generated` is used to denote a class or a function that has been generated using an automation script. This tag should be used **to warn to not change the code**, since the change will be overwritten by the automation script.

https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#55-generated

**Comment by froschdesign** [comment]
@pmjones 
It's good to see that things are moving forward here.
How can we help? Is there a plan that can be looked at?

**Comment by pmjones** [comment]
@froschdesign sorry to take so long to respond -- no, nothing to help with other than for me to do the work, which is in progress and substantially complete. Look at https://github.com/atlasphp/Atlas.Testing/tree/2.x-wip for an example of the generated classes, and look especially at the Related classes using attributes to define relationships.

**Pull request merged**
